"use client";
import HeaderBar from "./Components/navigation/HeaderBar.jsx";
import { EmailProvider } from "./Context/Email/UserEmail.js";
import { AuthProvider } from "./Context/Login/UserLoginContext.js";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <EmailProvider>
        <html lang="en">
          <body className="font-serif tracking-widest  scrollbar-thin scrollbar-thumb-slate-500">
            <HeaderBar />
            {children}
          </body>
        </html>
      </EmailProvider>
    </AuthProvider>
  );
}
